version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: ./builder/Dockerfile.production
            args:
                NODE_ENV: ${NODE_ENV}
                NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
                NEXT_PUBLIC_WEB_URL: ${NEXT_PUBLIC_WEB_URL}
        command: sh -c "npm start"
        deploy:
            resources:
                limits:
                    memory: 2048m
