version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: ./builder/Dockerfile.development
        command: npm run dev
        volumes:
            - ./:/app
        environment:
            - NEXT_PUBLIC_APP_NAME
            - NEXT_PUBLIC_WEB_URL
